name: CMake build (xmon)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libncurses5-dev libncursesw5-dev dpkg-dev

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build

    # ---------------- DEB PACKAGE ----------------
    - name: Create DEB package structure
      run: |
        mkdir -p pkg/usr/local/bin
        mkdir -p pkg/DEBIAN

        cp build/xmon pkg/usr/local/bin/

        printf "Package: xmon\nVersion: 0.1\nSection: utils\nPriority: optional\nArchitecture: amd64\nMaintainer: xmon-dev\nDescription: Linux system monitor (process/thread/memory TUI)\n" > pkg/DEBIAN/control

    - name: Build DEB
      run: dpkg-deb --build pkg xmon.deb

    - name: Upload DEB artifact
      uses: actions/upload-artifact@v4
      with:
        name: xmon-deb
        path: xmon.deb
